name: CML
on: [push]
jobs:
 train:
    runs-on: [self-hosted, cml, gpu]
    steps:
    
    - uses: actions/checkout@v3
    - name: Train model
      env: 
        CI_COMMIT_MESSAGE: Updated the experiment results
        CI_COMMIT_AUTHOR: vijayreddysamula
        CI_COMMIT_MAIL: vijay.samula@e-terry.de
      run: |
        git checkout experiment_iab
        pip install dvc
        dvc pull --run-cache
        pip install -r requirements.txt
        rm -rf /runs/train/exp*
        dvc repro
        dvc add ../datasets/yolo_datasets --external
        dvc add runs/train/exp --external --file exp.dvc
        dvc push
        
        
      
    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.CHECKOUT_TOKEN}}
      run: | 
        echo "## Metrics: Precision, Recall, mAP_0.5">> report.md
        cat runs/train/exp/results.csv >> report.md
        
        cml comment create report.md